language: java

git:
 quiet: false

before_install:
 - gradle installWrapper

script:
 - gradle buildCore
 - gradle test
 
job:
 include:
 - jdk: openjdk8
   os: linux
 - jdk: openjdk11
   os: linux
 - jdk: openjdk11
   os: osx
 allow_failures:
 - os: osx

Notifications:
 email:
  recipients:
  - s4paheis@uni-trier.de
  on_success: always
  on_failure: always