#Autor: Paul Heisterkamp - 1297417
name: CI_build

on:
  push:
    branches:
    - main
pull_request:
  types: [opened, synchronized, reopened]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
          with: 
            fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v1
          with:
            java-version: 11
      - name: Grant execution permission
        run: chmod +x gradlew
      - name: Build_gradle
        run: ./gradlew build
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew build sonarqube --info




